### ISSUE TITLE
list iterator not dereferencable

### ISSUE THREAD

**Issue by Antidote00** [rodschulz/CC72Y_PBA#1]
Hi rod,

I'm trying to use your implementation for creating a mesh out of a point cloud created with the Kinect v1 Sensor. 
My cloud looks like this: http://pastebin.com/WQNt6P7J (x y z norm_x norm_y norm_z) in Meshlab and the PCL::Viewer it looks just fine. 
Here is the main.cpp: http://pastebin.com/s35WW1A0 

In Front.cpp at         

removeEdgePoints(*pos); (Line 84)  

I get the error: _DEBUG_ERROR("list iterator not dereferencable"); This happens after finding the first seed and adding a point. I'm using Visual Studio 2013 and PCL 1.7.2. 

Do you have any idea how to fix this? 

Thanks,
Toni

**Comment by rodschulz** [comment]
Hi Toni, 

First of all, I've never compiled or run this in Visual Studio, I developed it in Linux, using gcc, so you might stumble on some compatibility issues. I can't say there are any because I don't know, but just a little disclaimer.

Regarding your error, usually that happens when an iterator points to nothing or something has corrupted the memory. In this case I think the problem might be because I'm erasing the element from the container (line 83) and then checking if I can remove any vertex from the front (line 84), so you could try to swap those lines and see what happens. You should also do the same fix on lines 128 and 129, where the same operation is done.

I find this interesting because while I was implementing the Front class I thought that might happen and tried it both ways (erase from container and then remove the points and viceversa), but none of them failed.

Please let me know if that works for you.
Best.
Rodrigo.

**Comment by Antidote00** [comment]
EDIT 2: I'm an idiot sorry. Didn't saw the mask you are using above. Thanks for your great help! And keep up the good work! 

EDIT: 

I have found the problem. As you said, it might be a problem of vc12. I swapped Line 83-84 and 128-129 and changed Line 84 and 129 as follows:

From <code> front.erase(pos); </code> to <code>pos = front.erase(pos); </code>

The code is running fine now and i got an .off file after 1 - 2 seconds as result. Sadly, MeshLab can't open it. Do you have any idea whats the problem with it? I also tried RoffViewGL, no luck. Here is my output: https://paste.ee/p/ujUcU 

br,
Toni

Hi Rodrigo,

thanks for your fast answer! I had already tried that, it results in the same error, but now at         <code>_pivoter.setUsed(_data.first); </code> (Line 90).<code> _data.first </code>is not empty, what confuses me most. In Line 87 the <code>list<EdgePtr>::iterator pos; </code>looks like this:

![iteratorpos](https://cloud.githubusercontent.com/assets/4086468/8591062/2660f78a-2626-11e5-81e7-a85066234054.PNG)

so it's pointing into the deep blue. I hope this is no compatibility issues with the vc12 compiler. What version of gcc are you using? 

br,
Toni

**Comment by rodschulz** [comment]
Hi Toni, 

It's great to hear it finally worked for you. The OFF files can be opened using Geomview (http://www.geomview.org/download/), sadly there's no binaries available for Windows, but can be compiled from source. Anyway, the OFF format it's pretty well known, so I believe there must exist some other app available for Windows.

Best.
Rodrigo.
